### ISSUE TITLE
Valid configuration values for intializationOptions and .vscode/settings.json

### ISSUE THREAD

**Issue by MichaelAllenHardeman** [georgewfraser/java-language-server#100]
I would love to have some documentation as to what fields and values are accepted in these two configuration sources. 👍

**Comment by georgewfraser** [comment]
Autocomplete and hover provides this within settings.json:

<img width="739" alt="docs" src="https://user-images.githubusercontent.com/1369240/63641088-80ff8b80-c65d-11e9-8c99-b8ec90422656.png">

Also you can find the same docs in the GUI version of user settings:

<img width="979" alt="settings" src="https://user-images.githubusercontent.com/1369240/63641100-a2607780-c65d-11e9-8477-993fc00f7fc6.png">
