### ISSUE TITLE
Request: Continue marking releases in github

### ISSUE THREAD

**Issue by liamsreya** [georgewfraser/java-language-server#104]
Hey @georgewfraser, if it can fit into your workflow requesting you continue to mark official releases as tags or even better github releases so that those of us building from source (or more accurately running the `./scripts/link_[os].sh`) can make sure we are building something that is considered stable. It appears that an issue I was trying to troubleshoot was solved by moving back to the `0.2.19` release which turned out to be this commit: georgewfraser/java-language-server@bf8a656fc6d . I found it by going to the vscode marketplace, seeing the current working version was in fact `0.2.19` and seeing the last modified date was May 18, then paging through the git logs to find this number in a commit message.

Separately the issue I hit was not having external dependencies picked up that were declared via `java.externalDependencies` and `java.classPath`. Happy to provide more details on this separately if useful, this was based off of commit georgewfraser/java-language-server@f04e293852349

**Comment by georgewfraser** [comment]
I just forget to run `git push --tags` sometimes.

**Comment by ayerswg** [comment]
No worries, thanks for pushing!

**Comment by GrimKriegor** [comment]
Hello there @georgewfraser.
Hate to be bumping a closed issue.
This is a refresh on the request to keep pushing the tags at your convenience.

I maintain the [java-language-server](https://aur.archlinux.org/packages/java-language-server/) AUR package for Arch Linux, which pulls the source archive based on the tags.
It has come to my attention that the [lastest available tag](https://github.com/georgewfraser/java-language-server/tags) is `v0.2.32` from nearly a year ago.

Thank you for your time!

**Comment by sudoforge** [comment]
This is a major issue for packagers. @georgewfraser I'd be happy to help you set up an auto-tag-and-release workflow if you so desire.

**Comment by UltraBlackLinux** [comment]
> Hello there @georgewfraser. Hate to be bumping a closed issue. This is a refresh on the request to keep pushing the tags, at your convenience.
> 
> I maintain the [java-language-server](https://aur.archlinux.org/packages/java-language-server/) AUR package for Arch Linux, which pulls the source archive based on the tags. It has come to my attention that the [lastest available tag](https://github.com/georgewfraser/java-language-server/tags) is `v0.2.32` from nearly a year ago.
> 
> Thank you for your time!

Something I noticed about your package: It bundles some java version which is incompatible with this project. The -git package works fine
