### ISSUE TITLE
Version v0.2.20 does not work on Linux

### ISSUE THREAD

**Issue by pappasam** [georgewfraser/java-language-server#105]
Version v0.2.19 works fine, but something between 19 and 20 breaks all functionality.

OS: Linux Mint 19.1
Env: Neovim 0.4.0dev (latest release)

Do you have any recommended tests I can run from the command line? Might be worth adding some CLI debugging strategies to the readme if you know of any. I'm having a bit of trouble debugging from within neovim.

**Comment by georgewfraser** [comment]
Clone the repo and run `mvn test` would be a good start.

**Comment by georgewfraser** [comment]
Ah I know what it is. I changed the name of the launcher and that broke the vim instructions. Sorry! I will put it back.

**Comment by georgewfraser** [comment]
Fixed by 40d42ee918120a4c0a6507d12748b5bae313464c

**Comment by pappasam** [comment]
Awesome, thanks! Awesome tool btw, and with your testing suggestion, I'll be more helpful in the future :)
