### ISSUE TITLE
Is java language server only available for java >= 9?

### ISSUE THREAD

**Issue by cheonhyangzhang** [georgewfraser/java-language-server#119]
Hi
when I tried to run /scripts/link_linux.sh to install the server, I go the following errors. 
```
./scripts/link_linux.sh: line 13: /usr/java/jdk1.8.0_181-amd64/bin/jlink: No such file or directory
```

After some research, I think it is because jink command is not available for jdk < 9
https://medium.com/azulsystems/using-jlink-to-build-java-runtimes-for-non-modular-applications-9568c5e70ef4

Is this true? 
Does it mean we can only use this java server for java version >= 9?

**Comment by georgewfraser** [comment]
You can only *build* JLS on recent versions of Java. Once it's built, it's standalone, so you can run it anywhere.
