### ISSUE TITLE
dist/linux/launcher missing

### ISSUE THREAD

**Issue by dproctor** [georgewfraser/java-language-server#122]
following the steps outlined at https://github.com/georgewfraser/java-language-server#installation-other-editors, i.e. running ``/scripts/link_linux.sh`, yields
```
./dist/linux/bin/
├── java
├── javac
├── jdb
├── keytool
└── serialver
```
My understanding of the directions suggests that there had ought to be a `launcher` executable in that directory, but none exists.

Any idea what I'm doing wrong?

Thanks!

```
$ java -version
java version "13.0.1" 2019-10-15
```

**Comment by georgewfraser** [comment]
Shoot, I changed the build so the command is now dist/lang_server_linux.sh, but I didn't update the instructions. Could you check this works and update the instructions?

**Comment by dproctor** [comment]
OK, thanks, I did notice that script before, and it does run (or at least running it without arguments displays usage information).

I'm trying to use this via ALE in vim, and the [readme](https://github.com/dense-analysis/ale/blob/master/doc/ale-java.txt) there says

```
===============================================================================
javalsp                                                      *ale-java-javalsp*

To enable Java LSP linter you need to download and build the vscode-javac
language server from https://github.com/georgewfraser/java-language-server.
Simply download the source code and then build a distribution:

   scripts/link_mac.sh

or

   scripts/link_windows.sh

This generates a dist/mac or dist/windows directory that contains the
language server. To let ALE use this language server you need to set the
g:ale_java_javalsp_executable variable to the absolute path of the launcher
executable in this directory.

g:ale_java_javalsp_executable                   *g:ale_java_javalsp_executable*
                                                *b:ale_java_javalsp_executable*
  Type: |String|
  Default: `''`

This variable must be set to the absolute path of the language server launcher
executable. For example:
>
  let g:ale_java_javalsp_executable=/java-language-server/dist/mac/bin/launcher
<
```

When I tried pointing g:ale_java_javalsp_executable to `launch_linux.sh`, `:ALEInfo` gives 
```
(executable check - failure) ~/watched-repos/java-language-server/dist/launch_linux.sh
```
so perhaps there's different usage for the new script that ALE needs to update to?

**Comment by georgewfraser** [comment]
Yes, dist/lang_server_{os}.sh is the new location.

If you're feeling ambitious, we should update the CI script to bundle a release of the language server for each OS, so the instructions for non-VSCode editors can be "download release X" rather than "build from source"

**Comment by dproctor** [comment]
OK, thanks, I'd be happy to take a look at updating that, as soon as I can get it working myself :)

Right now, I get

```
$ dist/lang_server_linux.sh 
Error: Could not find or load main class org.javacs.Main
Caused by: java.lang.ClassNotFoundException: org.javacs.Main
```

FYI
```
$ java --version
java 13.0.1 2019-10-15
Java(TM) SE Runtime Environment (build 13.0.1+9)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)
```

**Comment by JohnTheCoolingFan** [comment]
Same problem
```
$ dist/lang_server_linux.sh 
Error: Could not find or load main class org.javacs.Main
Caused by: java.lang.ClassNotFoundException: org.javacs.Main
```
```
$ java --version
openjdk 13.0.1 2019-10-15
OpenJDK Runtime Environment (build 13.0.1+9)
OpenJDK 64-Bit Server VM (build 13.0.1+9, mixed mode)
```

**Comment by VRanga000** [comment]
> Same problem
> 
> ```
> $ dist/lang_server_linux.sh 
> Error: Could not find or load main class org.javacs.Main
> Caused by: java.lang.ClassNotFoundException: org.javacs.Main
> ```
> 
> ```
> $ java --version
> openjdk 13.0.1 2019-10-15
> OpenJDK Runtime Environment (build 13.0.1+9)
> OpenJDK 64-Bit Server VM (build 13.0.1+9, mixed mode)
> ```

After some reverse-engineering, I was able to get the lang server to run on linux by first running:
```
mvn package -DskipTests
```
which creates the "classpath" dir with jars inside it:
```
➜  java-language-server git:(master) ls ./dist/classpath
gson-2.8.5.jar  java-language-server.jar  protobuf-java-3.9.1.jar
```
Then lang server runs:
```
➜  java-language-server git:(master) ./dist/lang_server_linux.sh
23:48:54.889    INFO    LSP connect     Reading messages from queue...
23:48:54.889    INFO    LSP$1MessageReader run  Placing incoming messages on queue...
```

**Comment by dproctor** [comment]
Vikas, thanks for looking into this.

Running the maven command does indeed resolve the issue for me!
