### ISSUE TITLE
How to get LSP to speak anything?

### ISSUE THREAD

**Issue by mehulmpt** [georgewfraser/java-language-server#144]
Hi! I've been spending too much time now on this without any success. Would mean a lot if you could help with this.

I'm trying to setup stdin/stdout communication with the LSP, but the server doesn't speak anything at all! I'm pretty sure I'm doing something wrong from my end. I've compiled the code and server starts successfully as show below, but I cannot get it to speak anything from terminal (no error messages, nothing). 

How do I get a basic run of this LSP so that it speaks the JSONRPC responses according to the standard? I'm testing in terminal right now as this stdout would be forwarded directly over a websocket to a language client.

Please see this photo for more information:

<img width="739" alt="Screenshot 2020-03-28 at 7 51 59 PM" src="https://user-images.githubusercontent.com/10388889/77825169-9d9cfe00-712d-11ea-903b-47b44f0b19fb.png">

**Comment by georgewfraser** [comment]
You're missing the [header part](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#headerPart) of the JSON-RPC message.

**Comment by mehulmpt** [comment]
Thanks! It works
