### ISSUE TITLE
Does it work with neovims' builtin LSP?

### ISSUE THREAD

**Issue by zupatisc** [georgewfraser/java-language-server#188]
I gave it a shot with lspconfig like so
````
local lspconfig = require('lspconfig')
local configs = require('lspconfig/configs')
configs.java_language_server = {
default_config = {
cmd = { '/usr/share/java/java-language-server/lang_server_linux.sh'};
filetypes = {'java'};
root_dir = lspconfig.util.root_pattern('build.gradle', 'pom.xml', '.git');
settings = {}
}
}
lspconfig.java_language_server.setup{}
````
Opening a java file with this config results in `Client 1 quit with exit code 1 and signal 0` but using LspInfo it reports that Server itself seems to be set correctly with regards to the cmd and the root_dir. Did I miss any other ways I could try to configure it? I couldn't find any possible options to pass to it. If someone else has got it to work or maybe just an idea on what to change I'd be happy to hear it.
Note: The server was installed through the AUR package.

**Comment by abenz1267** [comment]
i've just installed it through the AUR as well, works as expected (besides not finding dependencies with gradle).

If you installed it through the AUR, you can simply use 'java-language-server' as the cmd. no need to point o the script.

**Comment by jupblb** [comment]
I see there is already a default config available: https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#java_language_server

**Comment by zupatisc** [comment]
Yes, now there is a config after I made a PR for it :smiley: . I guess I can close this now too considering that it works.
