### ISSUE TITLE
Make javaconfig.json optional and try to read other config files

### ISSUE THREAD

**Issue by felixfbecker** [georgewfraser/java-language-server#2]
Eclipse generates a `.project` for a java project. The presence of this file could also indicate the root of a Java project. Along with it, Eclipse generates a `.classpath`, which is an XML file like this:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
    <classpathentry kind="src" path="src"/>
    <classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER"/>
    <classpathentry kind="con" path="org.eclipse.jdt.junit.JUNIT_CONTAINER/4"/>
    <classpathentry kind="output" path="bin"/>
</classpath>
```

It contains both the `sourcePath` setting (`<classpathentry kind="src"/>`), the `outputDirectory` (`<classpathentry kind="output"/>`) and the actual class paths (`<classpathentry kind="con">`). Eclipse does not have a feature to automatically export these into a text file this extension understands, support for this file would make it super easy to contribute to projects that use Eclipse.

Similarly, maybe we can take the presence of a `pom.xml` as the indication of a java project root aswell and get classpaths for Maven projects directly from the extension without someone having to add this configuration to their `pom.xml`?

Would do a PR :)

**Comment by georgewfraser** [comment]
This would be great. The reason I went with the javaconfig.json mechanism was just to get it working quickly. 

But I'm a little concerned about reading the xml files and trying to interpret them. These build tools are super configurable so depending on what plugins someone is using, the only way to figure out the classpath is to ask the build tool itself. 

I'd happily accept any PR that adds support for a particular type of config file, as long as it will work reliably on *real* config files with lots of complicated settings, and isn't just a hack of a common special case.

**Comment by georgewfraser** [comment]
If you want to work on this, you'll need to modify findJavaConfig in lib/Finder.ts

**Comment by georgewfraser** [comment]
As suggested in https://github.com/georgewfraser/vscode-javac/issues/3, I am going to adopt the language server protocol, and it looks like the config-finding logic may end up in Java rather than typescript code. This may affect the implementation of this feature.

**Comment by svenefftinge** [comment]
> But I'm a little concerned about reading the xml files and trying to interpret them. These build tools are super configurable so depending on what plugins someone is using, the only way to figure out the classpath is to ask the build tool itself.
Indeed. Not sure about maven but gradle has an API for tools to get that information. https://docs.gradle.org/current/userguide/embedding.html

I think (hope) maven has something similar. It's really hard otherwise to do the full resolution of a maven project.

**Comment by felixfbecker** [comment]
> I think (hope) maven has something similar.

My thought aswell

**Comment by georgewfraser** [comment]
I have refactored to use @svenefftinge implementation of the java language services protocol, which eliminates nearly all the Typescript code. This structure should now be stable. @felixfbecker, if you want to work on providing support for .project / .classpath files, you should be able to add them here https://github.com/georgewfraser/vscode-javac/blob/master/src/main/java/org/javacs/JavaLanguageServer.java#L355

**Comment by svenefftinge** [comment]
I would also be very interested in some component / code that can read project meta data to give me the compile-time (and runtime) classpath. We have many JVM languages to support, so maybe we could work on something that is reusable for others?

**Comment by georgewfraser** [comment]
I would suggest starting simple: a separate source file. If we make some good progress, it can be spun off as a separate module later.

**Comment by ecmel** [comment]
Hi, have you considered using Apache Felix (http://felix.apache.org/) for a modular approach. People can implement features and plugins on separate projects.

**Comment by shautvast** [comment]
in gradle it's simple:

task vscode << {    
    new File(projectDir, ".vsclasspath").text = configurations.runtime.asPath + ";"
    new File(projectDir, "javaconfig.json").text = '{"sourcePath": ["src/main/java", "src/main/resources","src/test/java","src/test/resources"],"classPathFile": ".vsclasspath","outputDirectory": "bin"}'
}

**Comment by xastor** [comment]
+1

Eclipse is (was) my development tool of choice, so I have a bunch (50+) of projects with .classpath files.. This would be so great!

**Comment by georgewfraser** [comment]
pom.xml is now read automatically: https://github.com/georgewfraser/vscode-javac/commit/ea0a36887374ee22e06a2009a602bcd5a479591a

@felixfbecker @xastor reading eclipse .project would be similar, PR welcome

**Comment by georgewfraser** [comment]
Dependency resolution has been significantly simplified. javaconfig.json is gone; source dirs are inferred automatically; externalDependencies are read automatically from Maven and Bazel or can be user-specified in [.vscode/settings.json](https://github.com/georgewfraser/vscode-javac#settings).

I think the only thing left to do to have automatic eclipse project support is to make sure that eclipse dependencies and folder structure are correctly discovered by InferConfig#buildClassPath,workspaceClassPath,outputDirectory,buildDocPath and add some tests to InferConfigTest
