### ISSUE TITLE
Starting client failed

### ISSUE THREAD

**Issue by timsexperiments** [georgewfraser/java-language-server#208]
I'm trying to use the [java-language-server](https://github.com/georgewfraser/java-language-server) vscode extension, but I am getting an error that the extension is not starting up:

```
[Error - 11:07:14 AM] Starting client failed
Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:403:11)
    at Object.spawn (child_process.js:570:9)
    at c:\Users\tdalt\.vscode-insiders\extensions\georgewfraser.vscode-javac-0.2.39\node_modules\vscode-languageclient\lib\main.js:357:40
```

Looks like that line is trying to run this script: [`dist\lang_server_windows.sh`](https://github.com/georgewfraser/java-language-server/blob/master/dist/lang_server_windows.sh). When I manually run that script, I get this error:

```
/mnt/c/Users/tdalt/.vscode-insiders/extensions/georgewfraser.vscode-javac-0.2.39/dist/launch_windows.sh: 13: /mnt/c/Users/tdalt/.vscode-insiders/extensions/georgewfraser.vscode-javac-0.2.39/dist/windows/bin/java: not found
```

which makes me think that something needs to run before that script runs.

Haven't looked much more into it than that. I have heard good things about this extension, but just haven't been able to get it working. Not sure if there's a bug, but would appreciate any help resolving this issue.

My `java -version` results in

```
openjdk version "11.0.9.1" 2020-11-04 LTS
OpenJDK Runtime Environment Zulu11.43+55-CA (build 11.0.9.1+1-LTS)
OpenJDK 64-Bit Server VM Zulu11.43+55-CA (build 11.0.9.1+1-LTS, mixed mode)
```

Operating System: Windows 11 Home v22000.493
VS Code: VSCode-Insiders (Latest version)

As a side note, if anyone has a good vscode bazel setup for Java, I would love to hear any tips on setup.

If this question is more appropriate for [stackoverflow](https://stackoverflow.com/questions/71288496/java-language-server-vscode-extension-starting-client-failed), I have posted it there as well and would appreciate any help I could get on it.

**Comment by georgewfraser** [comment]
Should be fixed now

**Comment by NogrTL** [comment]
@georgewfraser error is still there for me
