### ISSUE TITLE
Gradle/Android issues

### ISSUE THREAD

**Issue by nmilosev** [georgewfraser/java-language-server#23]
Hi! I was trying to setup your plugin to work with an Android project with Gradle. (I don't know gradle that well so bear with me) In the readme.md, I think this line is wrong:

```
ext.destFile = file("javaconfig.json")
        ext.config = [
            sourcePath: sourceSets.collect{ it.java.srcDirs }.flatten().collect{ relativePath(it) },
>>>            classPathFile: relativePath(tasks.getByPath(':vscodeClasspathFile').outputs.files.singleFile),
            outputDirectory: relativePath(new File(buildDir, 'vscode-classes'))
        ]
```

Upon removing `:` from the `:vsCodeClasspathFile` the gradle task finished successfully. If I leave it there:

```
$ ./gradlew vscode

FAILURE: Build failed with an exception.

* Where:
Build file '/home/nmilosev/Projects/android/alfaevid/android/app/build.gradle' line: 52

* What went wrong:
A problem occurred evaluating project ':app'.
> Task with path ':vscodeClasspathFile' not found in project ':app'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8.628 secs
```

Also I think it's a good idea to specify in the readme where to put your tasks in an android project - it should be under `android { }`.

Also the `javaconfig.json` file is a bit wrong:

```
{
    "sourcePath": [
        "app/src/androidTest/java",
        "app/src/debug/java",
        "app/src/main/java",
        "app/src/release/java",
        "app/src/test/java",
        "app/src/testDebug/java",
        "app/src/testRelease/java"
    ],
    "classPathFile": "app/build/classpath.txt",
    "outputDirectory": "app/build/vscode-classes"
}
```

and it should be:

```
{
    "sourcePath": [
        "src/androidTest/java",
        "src/debug/java",
        "src/main/java",
        "src/release/java",
        "src/test/java",
        "src/testDebug/java",
        "src/testRelease/java"
    ],
    "classPathFile": "build/classpath.txt",
    "outputDirectory": "build/vscode-classes"
}
```

**When these little problems are fixed, the plugin works fantastically fast and well, dare I say faster than OmniSharp**

Thanks for the plugin, works great so far!

**Comment by nmilosev** [comment]
A small update: android.jar was missing from classpath file, which in turn generated some errrors. By adding it manually (in my case ```/opt/android-sdk-linux/platforms/android-23/android.jar```) the plugin works fully and great.

Thanks again!

**Comment by airstep** [comment]
Didn't work for me... Applyed your suggestions but no highlightings for methods... etc

vscode version 1.5.3

**Comment by nmilosev** [comment]
It also depends where you open the project with VSCode, try opening in the same folder where your ```app``` folder is. Also check the log file, it is very verbose and it is how I fixed my issues in the first place. :)

**Comment by orionlee** [comment]
I still ran into some problems (see #34 duplicate class errors), after applying the suggestions here and more.

It is not clear to me yet whether the problem I encountered is specific to Android or not so I mention it here.

In addition to being an Android build, the project in question, [AntennaPod](https://github.com/AntennaPod/AntennaPod/), is slightly more complicated in that it has 2 sub-projects. The errors I face might be:
1. related to Android build
2. related to the fact there are 2 sub projects
3. issues inherent with current `vscode-javac`

I also tried reducing the 2 sub projects into 1 (from `vscode-javac` perspective) by manually create 1 single `javaconfig.json` (and `classpath.txt`) at the root directory instead. The problem still existed, however.

Help would be appreciated.

**Comment by orionlee** [comment]
Does `vscode-javac` support Android's `.aar` files in `classpath.txt` ? It it does not support `.aar` files, it definitely poses a problem for any Android project.

**Comment by georgewfraser** [comment]
VSCode uses javac under the hood. It talks directly to the javac API via tools.jar, but the effect is the same as if you ran 

`javac -classpath $(cat classpath.txt) ...`

So the question is, is javac compatible with `.aar`? I don't know, I've never used it myself.

**Comment by DonnieWest** [comment]
Over at artur-shaik/vim-javacomplete2 we use a Gradle init script to add tasks dynamically to the user's Gradle instance without them needing to modify their build files. We also have some logic on those tasks to automatically add AAR/Android platform files to the resulting classpath which can be found [here](https://raw.githubusercontent.com/artur-shaik/vim-javacomplete2/master/classpath.gradle)

Not sure when I'd get a chance to do it myself, but at the very least this should be able to be adapted to your README so everyone gets the benefits :)

**Comment by georgewfraser** [comment]
javaconfig.json has been eliminated in favor of automatic inference + [.vscode/settings.json](https://github.com/georgewfraser/vscode-javac#settings). That *should* make it simpler to get tricky projects working.
