### ISSUE TITLE
Start to publish 0.1.0

### ISSUE THREAD

**Issue by JiahuiJiang** [georgewfraser/java-language-server#33]
Right now vscode-javac is not publish to anywhere, in order to pull it in as a dependency to package with the distribution, we have to download the repo and build locally.
Is there anything that's blocking publishing 0.1? Can we setup a circle build (so that it can also run checks before merging changes into master) and maybe start to publish to bintray?

**Comment by georgewfraser** [comment]
It has to be published with `vsce` which requires my publisher key, so how would that work?

**Comment by gatesn** [comment]
@georgewfraser I think @JiahuiJiang is referring to the Java libraries, which can be published to maven central or elsewhere. Not the VSCode extension.

**Comment by georgewfraser** [comment]
Oh. I'm not really familiar to how to publish to Maven Central. CircleCI is running on this project so we could potentially use it for automation.

I think first we should make sure there's at least 1 user who actually wants to use this as a maven dependency though. The only scenario I can think of is if you want to re-use the language server with a non-VSCode editor.

**Comment by gatesn** [comment]
We are those users! Publishing the libraries does a couple of things (though a few code changes will need to be made):

* Lets people extend the language server to provide custom capabilities.
* Lets people more easily re-package the language server for different clients.
