### ISSUE TITLE
Support Java 9

### ISSUE THREAD

**Issue by limey-git** [georgewfraser/java-language-server#47]
_Java Language Support extension version 0.0.41_
_Visual Studio Code version 1.12.1_
_OS: ubuntu 12.04 LTS i386 [32-bit]_

With JDK 9 early access release installed on my linux  box, the extension fails to load with the  "_Java language support requires Java 8 (using /my/path/to/java-9/bin/java)_" error.

Any plans to make this extension work with JDK 9?

Thanks in advance.

**Comment by georgewfraser** [comment]
This project is based on the netbeans fork of tools.jar. [build-tools-jar/make.sh](https://github.com/georgewfraser/vscode-javac/blob/master/build-tools-jar/make.sh) is a script that builds it from source; going to Java 9 is simply a matter of changing the [version](https://github.com/georgewfraser/vscode-javac/blob/c5c13c349960616ea45618ed42f5697eb0fb6c69/build-tools-jar/Dockerfile#L49) we build.

However, last time I checked, the netbeans tools.jar Java 9 branch was not yet very stable, so I haven't done this yet.

**Comment by limey-git** [comment]
>  "&hellip;_the netbeans tools.jar Java 9 branch was not yet very stable_&hellip;"

My guess is that _instability_ is more than likely due to [_the non-existence of tools.jar in JDK 9_](http://bit.ly/ToolsRemoved).

**Comment by saad749** [comment]
now that jdk 9 is released, will there be support soon for jdk 9?

**Comment by J-Liu** [comment]
ping

**Comment by georgewfraser** [comment]
The main problem here is that JDK langtools, which was previously in tools.jar, was incorporated into the main java platform in Java 9. This project uses a custom build of langtools, but now when we attempt to load the custom build, we instead get the standard version. The solution is probably some kind of classloader hackery, I just haven't managed to figure it out yet.

**Comment by limey-git** [comment]
After you went _radio silent_ back in July, @georgewfraser, I went ahead and did some experimental hacking of my own—since I had some down-time back then. I got a local build to succeed with all the tests passing with JDK 9 (_the then-current ea build 169_).

I got the extension _kinda~sorta_ working in Code with JDK 9. Meaning, I could successfully import all the JDK classes from the java.base module (_and several other JDK publicly-exported modules_) into my non-jigsaw-a-fied projects...

----
![completion listing com.sun.*](https://user-images.githubusercontent.com/13301223/32699571-be8e4404-c7af-11e7-94e8-918838678ba2.png)
----
![completion listing com.sun.net.httpserver.*](https://user-images.githubusercontent.com/13301223/32699588-198a3278-c7b0-11e7-98f2-4c63f3b44668.png)
----


But I ran out of time when I got to that point, however. So I didn't do any jigsaw-related hacking. If I recall correctly, I might have managed to successfully compile a simple named module from a module-info.java file. But it's been a few months since I looked closely at the code, So I might be just imagining that part :¬)

I do recall that I encountered some funny business in the completion functionality. It struggles completing look-ups for certain publicly-exported JDK packages. But it does fine with the majority of packages and classes.

Since I never use any of the packages that the completion stuff couldn't complete, I didn't have the patience to try to figure out the problem. But since you know the code better than anybody else, getting completion to complete 100% of the time will probably be easy for you.

Probably your biggest hurdle to overcome on the way to JDK 9 support, is one particular upstream dependency: _Google Code's com.google.common.reflect.ClassPath_. I had to hack that too. 

If you could get Google to accept a relatively minor refactoring of _com.google.common.reflect.ClassPath_, plus get the extension to do the right thing with module-info.java files (_ie, jigsaw_) and figure out why completion is incomplete, there is hope of JDK 9 support for your extension.

**Comment by limey-git** [comment]
OK. So you're not the chatty type then, huh @georgewfraser? I can respect that ;¬)

You know your own code better than anybody. So naturally I defer to you as the undisputed authority of your extension's implementation. 

However, I have played around in two or three of your source files. I did so more as an exercise to acclimate myself to JDK 9, than anything else; certainly not with any expectation of patching your extension to support JDK 9 100% perfectly. 

Far be it for me to tell you how to suck eggs, @georgewfraser. But based on what I've learned so far from my JDK 9 acclimation exercise, I reckon there are some implementation details in your current code base — [_as of Nov 18, 2017_](http://bit.ly/gwf10Nov17) — that are doomed to failure with JDK 9. IMHO.

In particular, any dependence that your implementation might have on [_URLClassLoader_](http://bit.ly/URLcldr) is a potential breaking point. 

Plus if you're using reflection anywhere, you could run into problems. Because in JDK 9 it is, more often than not, necessary to explicitly "_open_" a depended-upon module in order to do reflection on any of its encapsulated implementations.

When I say, "_doomed_", I mean that [_currently_](http://bit.ly/gwf10Nov17) your code looks like it has a dependency on things that [_simply no longer exists in JDK 9_](http://bit.ly/JEP260). I've also noticed  in your most recent commits that you aren't using any of JDK 9's so-called "_permit illegal access_" flags anywhere. So if you don't refactor your implementation to use JDK 9-sanctioned replacements—_plus explicity open up the default encapsulation_ — I would be surprised if you got it to work with sheer _"hackery_" alone.

To give you some insight into what I'm on about when I say "_no longer exists_", here are the last few lines output by [_jdeps'_](http://bit.ly/jdepsJDK9) static analysis of your fat-jar.jar...

| JDK Internal API | Suggested Replacement |
|  ---------------  | ------------------------ |
| sun.misc.Launcher | Removed. See http://openjdk.java.net/jeps/260 |
| sun.misc.URLClassPath | Removed. See http://openjdk.java.net/jeps/260 |
| sun.misc.Unsafe | See http://openjdk.java.net/jeps/260 |
| sun.reflect.annotation.AnnotationParser | Removed. See http://openjdk.java.net/jeps/260 |
| sun.reflect.annotation.AnnotationType | Removed. See http://openjdk.java.net/jeps/260 |
| sun.reflect.annotation.EnumConstantNotPresentExceptionProxy | Removed. See http://openjdk.java.net/jeps/260 |
| sun.reflect.annotation.ExceptionProxy | Removed. See http://openjdk.java.net/jeps/260 |

[_Like I said before_](http://bit.ly/ToolsRemoved), there is no such thing as a "_tools.jar_" in JDK 9. Please forgive me for being pedantic. But it would behooves _anybody_ doing anything with JDK 9, to stop thinking in terms of "_using classes in jar files_", and start thinking in terms of "_using classes in modules_".

**Comment by georgewfraser** [comment]
@limey-git I think you're misunderstanding a bit how this extension works. It doesn't use the system tools.jar; it bundles it's own build of tools.jar. That's what [build-tools-jar/make.sh](https://github.com/georgewfraser/vscode-javac/blob/a36635d29240ea4f460149b65e1f4281ab7725c3/build-tools-jar/make.sh) does. It's technically the netbeans fork of javac, which has better error recovery.

I spent some fiddling with this last weekend and got it to [load the bundled tools.jar in Java 9 using a custom classloader](https://github.com/georgewfraser/vscode-javac/commit/2bd269b5338689bcc0492e28b5646ecb7c22fb5b), and [fixed the way it figures out the system classpath](https://github.com/georgewfraser/vscode-javac/commit/9dd69d0c1add5d38e981fd53116270c9f56d1fb6). That was enough to get it to run on Java 9, but when it tries to actually read Java 9 modules (which are basically jars) it fails:

```
Caused by: java.lang.NullPointerException
	at com.sun.tools.javac.file.Locations.getPathEntries(Locations.java:149)
	at com.sun.tools.javac.file.Locations.getPathEntries(Locations.java:134)
	at com.sun.tools.javac.file.Locations.access$000(Locations.java:71)
	at com.sun.tools.javac.file.Locations$BootClassPathLocationHandler.computePath(Locations.java:617)
	at com.sun.tools.javac.file.Locations$BootClassPathLocationHandler.lazy(Locations.java:643)
	at com.sun.tools.javac.file.Locations$BootClassPathLocationHandler.getLocation(Locations.java:577)
	at com.sun.tools.javac.file.Locations.getLocation(Locations.java:678)
	at com.sun.tools.javac.file.JavacFileManager.getLocation(JavacFileManager.java:803)
	at com.sun.tools.javac.file.JavacFileManager.list(JavacFileManager.java:617)
	at javax.tools.ForwardingJavaFileManager.list(ForwardingJavaFileManager.java:76)
	at org.javacs.IncrementalFileManager.list(IncrementalFileManager.java:73)
	at com.sun.tools.javac.api.ClientCodeWrapper$WrappedJavaFileManager.list(ClientCodeWrapper.java:233)
	... 33 more
```

The problem is that it's the Java 8 compiler trying to read a Java 9 module. I think the best path forward here is to:
- Modify [build-tools-jar](https://github.com/georgewfraser/vscode-javac/tree/a36635d29240ea4f460149b65e1f4281ab7725c3/build-tools-jar) to build the equivalent of tools.jar for Java 9
- Refactor vscode-javac to target Java 9 instead of Java 8
- Use jlink to create a zero-dependency launcher for each platform, so we're not dependent on what version of java the user is running

I'm not 100% sure it's worth it to invest a ton of effort in this plugin though. Microsoft is pushing [their own Java plugin](https://code.visualstudio.com/docs/languages/java) hard. It works by running a headless eclipse in the background, which I think is a terrible design but it's the "official plugin" now and has had a lot of polish, so everyone tends to use it. I'm curious, what is your interest in this plugin @limey-git ?

**Comment by limey-git** [comment]
Thanks for replying @georgewfraser.

> _I'm curious, what is your interest in this plugin @limey-git ?_

Like I said earlier. My interest in this plugin is mainly that it is some JDK 8-centric, open-source code (_chosen at random_) that I can play with as a means to get some practice using JDK 9.

I thought it would be the neighborly thing to do to share with you — _and anybody else who might be interested_ — any tips or gotcha's I discovered in that process.

> _It doesn't use the system tools.jar_

I think _you_ misunderstood why I mentioned tools.jar. But never mind ;¬)

> _The problem is that it's the Java 8 compiler trying to read a Java 9 module_

Are you saying you tried to use a JDK 8 compiler on code you're targeting to run under Java 9? Now that, I _*do*_ misunderstand.

> _Microsoft is pushing [their own Java plugin](https://code.visualstudio.com/docs/languages/java) hard._ 

Again. Forgive me for being pedantic. But actually, that's Red Hat's Java plugin they're pushing. Not Microsoft's.

> _Modify [build-tools-jar](https://github.com/georgewfraser/vscode-javac/tree/a36635d29240ea4f460149b65e1f4281ab7725c3/build-tools-jar) to build the equivalent of tools.jar for Java 9_

In that case, you definitely want to Google, "[_JDK 9 split packages_](http://bit.ly/SplitPkg)".

Good luck @georgewfraser :¬)

**Comment by dvogel** [comment]
FWIW I'd rather use this than the headless eclipse plugin that Microsoft provides.

**Comment by georgewfraser** [comment]
@dvogel There's a couple people who have gotten interested in this project as a way to provide Java support in other (non-vscode) editors, and I've been playing with a [Kotlin language server](https://github.com/georgewfraser/kotlin-language-server) and getting some good ideas that could cross back over to this plugin, so there's hope 😄

**Comment by zetelight** [comment]
It is nice to the progress! Thank you for your work.
Just a little curious. Will it support Java 10 later? 
The Ubuntu 18.04 LTS brings Java 10 by default so It is a little annoying when it popped "Java language support requires Java 8" error. (Hence, I re-install Java 8 and set it as default)

**Comment by eerokosk** [comment]
@zetelight 

Java 10 support is quite good level at the moment. At least if you are using Gradle (i haven't tested with Maven). Even projects with Lombok are working nicely. I'm using Azul's openjdk with following .code-workspace:

``
{
        "folders": [
                {
                        "path": "."
                }
        ],
        "settings": {
                "java.home": "C:\\Java\\JDK\\java-10",
                "java.configuration.updateBuildConfiguration": "automatic",
                "java.jdt.ls.vmargs": "-javaagent:C:\\Java\\lombok\\1.18.0\\lombok.jar -Xbootclasspath/a:C:\\Java\\lombok\\1.18.0\\lombok.jar"
        }
}
``

**Comment by georgewfraser** [comment]
It now runs on Java 10

**Comment by zorcic** [comment]
> Broken again in Java 11? I only get "Couldn't start client Java Language Server".

same here

**Comment by georgewfraser** [comment]
Dang, that's frustrating. Can you try to get some log info from "Output / Java":

<img width="1217" alt="screen shot 2019-02-09 at 11 25 00 am" src="https://user-images.githubusercontent.com/1369240/52524001-764f4d00-2c5d-11e9-8cd8-3db3866a3367.png">

And if that isn't available, the VSCode js console `Help / Toggle Developer Tools`

**Comment by blackwind** [comment]
```
[Error - 1:52:31 AM] Starting client failed
Launching server using command c:\Users\blackwind\.vscode\extensions\georgewfraser.vscode-javac-0.2.13\dist\windows\bin\launcher failed.
```

When I run `launcher.bat` manually, it appears to work as intended:

```
01:52:42.106    INFO    org.javacs.lsp.LSP connect      Reading messages from queue...
01:52:42.106    INFO    org.javacs.lsp.LSP$1MessageReader run   Placing incoming messages on queue...
```

**Comment by drujd** [comment]
This is still an issue...

**Comment by mkpaz** [comment]
The same in Java 12. :( Well if server can't be started with newer Java versions it means that this project 90% dead.

**Comment by georgewfraser** [comment]
It works up to Java 11 right now. Now that it's packaged as a standalone executable, it's pretty easy to roll forward a version, I just haven't gotten around to Java 12 just yet.
