### ISSUE TITLE
Infinite Loading on error suggestion

### ISSUE THREAD

**Issue by jaxoncreed** [georgewfraser/java-language-server#50]
When I hover over highlighted errors and wait for a suggestion, the tooltip freezes with a "Loading" message (see attached image). Below are some messages from the Java Console when I start the project in code:

`[Info  - 6:04:59 PM] Connection closed
[Warn  - 6:04:59 PM] Unexpected params 'java.lang.Void@762ca2b4' for 'public default void org.eclipse.lsp4j.services.LanguageServer.initialized()' is ignored
[Warn  - 6:04:59 PM] Unsupported notification method: $/setTraceNotification
[Info  - 6:04:59 PM] Lint file:///Users/m/git/******/src/main/java/***/*****/******/dbpojo/Test.java
[Info  - 6:04:59 PM] Emit effective pom for /Users/m/git/moppet/pom.xml to /var/folders/16/jklb51p1409_wpyx8t78y8bm0000gn/T/effective-pom2290539182353371595.xml
[Info  - 6:05:08 PM] Emit classpath to /var/folders/16/jklb51p1409_wpyx8t78y8bm0000gn/T/classpath2404906236906906885.txt
 `

Here's some information about my configuration:

- Mac OS Sierra 10.12.5
- Java 1.8.0_131
- I also have Language Support for Java by Red Hat installed. But it seems to be the same result without it.
- Maven 4.0.0

![vscodeproblem](https://user-images.githubusercontent.com/5464743/27990262-bf4287d8-6405-11e7-87ec-87c2f2cee8c3.png)

**Comment by georgewfraser** [comment]
External dependency resolution has been considerably simplified and this may work better for you now.
