### ISSUE TITLE
goto defenition only works on .java files.

### ISSUE THREAD

**Issue by clankill3r** [georgewfraser/java-language-server#53]
I made 2 files. One is called `Test.java` the other one `Test.pde` (The extention used by processing www.processing.org).

This is the code:
```java
class Test {    
    void foo() {
        String s = "dfsdf";
    }
}
```
The language mode is for both set at java.

<img width="361" alt="screen shot 2017-08-08 at 16 49 27" src="https://user-images.githubusercontent.com/738650/29077995-8fde8cf0-7c59-11e7-92fe-70f054d66224.png">

The `goto defenition` only works for the file with the java extention. 
<img width="310" alt="screen shot 2017-08-08 at 16 49 49" src="https://user-images.githubusercontent.com/738650/29078013-9fa57432-7c59-11e7-9e00-46e68ef4a895.png">

(As in that brings me to String.class where I can view the code)

**Comment by georgewfraser** [comment]
The concept of "language mode" isn't part of the language server protocol, so it's not possible to learn about non-.java extensions from the point of view of a language server.
