### ISSUE TITLE
Dependency Parsing issue on linux

### ISSUE THREAD

**Issue by MichaelAllenHardeman** [georgewfraser/java-language-server#75]
After cloning the repo and getting the correct java version installed, when  I run mvn package to build the standalone .jar file I'm getting some failures in the InferConfigTest.

Specifically, these 3 tests fail:
[dependencyList](https://github.com/georgewfraser/java-language-server/blob/master/src/test/java/org/javacs/InferConfigTest.java#L66)
[thisProjectClassPath](https://github.com/georgewfraser/java-language-server/blob/master/src/test/java/org/javacs/InferConfigTest.java#L71)
[thisProjectDocPath](https://github.com/georgewfraser/java-language-server/blob/master/src/test/java/org/javacs/InferConfigTest.java#L78)

Debugging it a bit, I suspect there is a character encoding issue.
When it's parsing the stdout from `mvn dependency:list`. There is some junk in the line string that looks like encoding issue that causes the regex [here](https://github.com/georgewfraser/java-language-server/blob/master/src/main/java/org/javacs/InferConfig.java#L337) to not match.

The lines values coming into this function look like the following:
```
[[1;34mINFO[m] Scanning for projects...
[[1;34mINFO[m] 
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;34mINFO[m] [1mBuilding javac-services 0.1-SNAPSHOT[m
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;34mINFO[m] 
[[1;34mINFO[m] [1m--- [0;32mmaven-dependency-plugin:2.9:list[m [1m(default-cli)[m @ [36mjavac-services[0;1m ---[m
[[1;34mINFO[m] 
[[1;34mINFO[m] The following files have been resolved:
[[1;34mINFO[m]    org.openjdk.jmh:jmh-generator-annprocess:jar:1.21:provided:/home/user/.m2/repository/org/openjdk/jmh/jmh-generator-annprocess/1.21/jmh-generator-annprocess-1.21.jar
[[1;34mINFO[m]    org.apache.commons:commons-math3:jar:3.2:test:/home/user/.m2/repository/org/apache/commons/commons-math3/3.2/commons-math3-3.2.jar
...
```

I think there are some wide characters mixed into the output. I tried messing with the CharacterSet for the InputStreamReader and couldn't remove the junk. Do you have some ideas as to how to fix this issue?

**Comment by georgewfraser** [comment]
You probably need to pass an extra argument to InputStreamReader here: https://github.com/georgewfraser/java-language-server/blob/master/src/main/java/org/javacs/InferConfig.java#L326

**Comment by MichaelAllenHardeman** [comment]
@georgewfraser I've tried "UTF-8", "UTF-16", "UTF_16BE", "UTF-16LE", and "ISO_8859_1"

No dice on any of them

**Comment by MichaelAllenHardeman** [comment]
In terminal, the $LANG variable indicates it should be UTF-8 input

$ echo $LANG
en_US.UTF-8

**Comment by MichaelAllenHardeman** [comment]
making the regex a bit more permissive solved the issue, but I'm not sure if that's a good solution.

`private static Pattern DEPENDENCY = Pattern.compile(".*\\s+(.*:.*:.*:.*:.*):(/.*)$");`

**Comment by georgewfraser** [comment]
I wonder if maybe it's a maven problem? Making the regex more permissive is a totally acceptable solution, do you mind making a PR?

**Comment by georgewfraser** [comment]
(with a test, ideally)

**Comment by MichaelAllenHardeman** [comment]
The reason I'm not sure if the solution is good is several reasons. I have no idea of the actual cause. Maybe it's because I'm on OpenJDK. Maybe the linux distro I'm using is quirky. Maybe it's not an encoding issue since changing the input encoding didn't fix it. I'm not really sure.

**Comment by MichaelAllenHardeman** [comment]
@georgewfraser OOHHHH. They might be ANSI control sequences that control the color of the text

**Comment by MichaelAllenHardeman** [comment]
Adding the -B option to the mvn command removes the console text coloring.

**Comment by MichaelAllenHardeman** [comment]
#76
