### ISSUE TITLE
Repository is huge to clone due to historical src.zip contained in git history

### ISSUE THREAD

**Issue by leighmcculloch** [georgewfraser/java-language-server#89]
This repository is pretty huge to checkout, 50mb+, because it has in it's git history a src.zip file containing all Java source. Would it be worth using this process to purge it from the history to slim the project down?

https://help.github.com/en/articles/removing-sensitive-data-from-a-repository

**Comment by leighmcculloch** [comment]
![](https://i.jif.wtf/10.7c78c9f59ccf7d2d7b900f2fd26b30a6.gif)

@georgewfraser Do you have thoughts of 👍 or 👎 on this? If 👎 I'll close this issue.

**Comment by georgewfraser** [comment]
Yeah I think this makes sense.

**Comment by leighmcculloch** [comment]
Is offer to open a pr, but I don't think this can be done on a pr. You're the only person that can do it.

**Comment by georgewfraser** [comment]
It is done.

**Comment by leighmcculloch** [comment]
Woah! Talk about fast turn around!!! Thanks!
