### ISSUE TITLE
Can't read property textDocumentSync in VSCode

### ISSUE THREAD

**Issue by SyamSundarKirubakaran** [georgewfraser/java-language-server#97]
I have the language Server set up locally by cloning it and building using,
```
npm install -g vsce
npm install
./scripts/build.sh
```
The extension is been successfully installed but it doesn't seem to sync up with any of the locally created java files. It creates an exception .i.e,

![Screenshot 2019-05-18 at 8 50 44 AM](https://user-images.githubusercontent.com/26897680/57963989-df281e80-794a-11e9-80d4-b1ff0ca86cee.png)

@georgewfraser any clue on fixing this.!?

**Comment by georgewfraser** [comment]
This was a temporary problem with vscode-language-client, since fixed
